# Generated by Django 4.2.7 on 2023-11-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateField(),
        ),
    ]
