# Generated by Django 4.2.7 on 2023-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_customer_managers_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_customer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
