# Generated by Django 4.2.7 on 2023-12-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivery', 'delivery'), ('not delivery', 'not delivery')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
