# Generated by Django 4.2.7 on 2023-12-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivery', 'delivery'), ('not delivery', 'not delivery')], default='not delevery', max_length=20),
        ),
    ]
