# Generated by Django 4.2.7 on 2023-12-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivery', 'delivery'), ('not delivery', 'not delivery')], default='not delivery', max_length=20),
        ),
    ]
